version: "3.7"

services:
  portainer:
    image: portainer/portainer:alpine
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/management/portainer:/data"
    ports:
      - "8000:8000"
      - "9000:9000"
    deploy:
      placement:
        constraints:
          - node.role == manager

  swarm-cronjob:
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Denver"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager

